export default {
  seo: {
    title: 'Floor planner for modular homes | NVC Home4You',
    description:
      'Interactive floor planner for container modules and box houses. Draft layouts, walls, doors, windows, finishes, and export a printable plan.',
    breadcrumb: 'Floor planner',
  },
  planner: {
    title: 'Floor plan builder',
    subtitle: '{area} m² · {w}×{d} {unitM}',
    show: 'Show',
    hide: 'Hide',
    zoom: 'Zoom',
    legend: 'Legend / How to use',
    legendHint: 'Quick guide + shortcuts',
    legendRoom: 'Drag to create a room. Rooms cannot overlap; choose type and floor finish from the panel.',
    legendWall: 'Drag to draw an interior wall segment (auto axis-aligned). Doors snap to any wall; windows snap to exterior walls only.',
    legendOpenings: 'Click to place. Switch to Select to drag along a wall. Doors support Flip swing / hinge in the Inspector.',
    legendSelect: 'Click an element to inspect it. Drag rooms to move them with snapping and no-overlap protection. Drag doors and windows to reposition them.',
    legendPan: 'Use the Pan tool to move the view. Use the mouse wheel to zoom. The plus/minus buttons work too.',
    legendSnapTitle: 'Snapping & multi-place',
    legendSnap: 'Grid snap is {grid}. Wall/room snap is {align}. Hold ALT to temporarily disable snapping. Hold SHIFT while moving a room to constrain the axis. Multi-place is currently {multi}.',
    keyAlt: 'Disable snapping while dragging',
    keyShift: 'Constrain axis while moving rooms',
    keyEsc: 'Release canvas capture (click the canvas to capture again)',
    keyV: 'Select tool',
    keyR: 'Room tool',
    keyW: 'Wall tool',
    keyD: 'Door tool',
    keyN: 'Window tool',
    keyP: 'Pan tool',
    model: 'Model',
    tools: 'Tools',
    roomSettings: 'Room settings',
    type: 'Type',
    floorFinish: 'Floor finish',
    grid: 'Grid',
    multiPlace: 'Multi-place',
    multiPlaceHint: 'Keep the current tool active after each placement (walls, doors, windows, rooms).',
    snapGrid: 'Grid snap',
    snapAlign: 'Wall / room snap',
    snapHint: 'ALT = temporarily disable snapping · SHIFT = constrain axis while moving rooms',
    objects: 'Objects',
    rooms: 'Rooms',
    openings: 'Doors & windows',
    walls: 'Walls',
    locked: 'Locked',
    inspector: 'Inspector',
    name: 'Name',
    delete: 'Delete',
    flipSwing: 'Flip swing',
    flipHinge: 'Flip hinge',
    outside: 'Outside',
    plan: 'Plan',
    units: 'Units: meters',
    resetView: 'Reset',
    clear: 'Clear',
    undo: 'Undo',
    redo: 'Redo',
    showPanel: 'Show panel',
    hidePanel: 'Hide panel',
    downloadLayout: 'Download layout',
    loadLayout: 'Load layout',
    exportPdf: 'Export PDF',
    loadLayoutError: 'Could not open that saved layout file.',
    captureOn: 'Canvas controls active — press Esc to release',
    captureOff: 'Click the canvas to capture controls',
    windowOnlyExterior: 'Windows can be placed only on exterior walls.',
    on: 'ON',
    off: 'OFF',
    snapStatus: 'Snap: {grid} / {align} (ALT disables)',
    unitCm: 'cm',
    unitM: 'm',
    tool: {
      room: 'Room',
      wall: 'Wall',
      door: 'Door',
      window: 'Window',
      select: 'Select',
      pan: 'Pan',
    },
    tip: {
      room: 'Drag to create a room.',
      wall: 'Drag to draw an interior wall segment.',
      door: 'Click a wall to place a door.',
      window: 'Click an exterior wall to place a window.',
      select: 'Select an element. Delete removes it.',
      pan: 'Drag to pan. Wheel to zoom.',
    },
    models: {
      c6x3: 'Container 6×3',
      c7x3: 'Container 7×3',
      c8x3: 'Container 8×3',
      b37: 'Box house 37 m²',
      b57: 'Box house 58 m²',
      b73: 'Box house 73 m²',
    },
    roomTypes: {
      living: 'Living',
      bed: 'Bedroom',
      kitchen: 'Kitchen',
      bath: 'Bathroom',
      office: 'Office',
      storage: 'Storage',
    },
    finishes: {
      wood: 'Wood',
      laminate: 'Laminate',
      spc: 'SPC',
      tile: 'Tile',
      pvc: 'PVC',
      concrete: 'Concrete',
    },
  },
}
