using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using Models;

namespace Services;

/// <summary>
/// Per-product &lt;head&gt; tags for the gallery detail pages, built at request time.
///
/// WHY THIS IS NOT IN THE BUILD-TIME MANIFEST. Every other route's tags come from
/// wwwroot/seo-manifest.json, generated by scripts/generate-seo-manifest.mjs from the
/// static route table. Products cannot work that way: they are rows in the database that
/// staff add and rename through the admin panel, so a manifest baked at build time would
/// be wrong the first time somebody edits a title and would need a redeploy to correct.
///
/// What this replaces was worse than "no tags". A path under /{locale}/gallery/ was a known
/// SPA route with no manifest entry, so the DEFAULT block stayed in the shell — and that
/// block carries the homepage title and, fatally, &lt;link rel="canonical" href="/"&gt;. Every
/// product URL was therefore telling Google it was a duplicate of the homepage, while
/// sitemap-gallery.xml submitted all of them. A missing canonical is a guess; a wrong one
/// is an instruction.
///
/// Reads through GalleryService, which is IMemoryCache-backed (10 min), so this costs a
/// dictionary lookup on the hot path rather than a query per crawl.
/// </summary>
public sealed class GallerySeoService
{
    private readonly GalleryService _gallery;

    public GallerySeoService(GalleryService gallery) => _gallery = gallery;

    /// <summary>
    /// Outcome of resolving a gallery detail path.
    ///
    /// NotAProductPath and ProductNotFound are deliberately different. The first means "not
    /// my business, carry on"; the second means the URL looks like a product but names one
    /// that does not exist, which is a genuine 404 — and used to be served as HTTP 200 with
    /// homepage metadata, i.e. a soft 404 for every mistyped or retired product URL.
    /// </summary>
    public enum Outcome { Resolved, ProductNotFound, NotAProductPath }

    public async Task<(Outcome Outcome, string? HeadTags)> TryBuildAsync(
        string path, CancellationToken ct)
    {
        if (!GallerySlugs.TryParsePath(path, out var locale, out var slug))
            return (Outcome.NotAProductPath, null);

        IReadOnlyList<GalleryItem> items;
        try
        {
            items = await _gallery.GetAsync(ct);
        }
        catch
        {
            // The catalogue is unreachable. Fall through to the default shell rather than
            // 404-ing a real product because a backing store hiccuped — a wrong 404 is
            // recorded by Google and takes far longer to undo than stale metadata.
            return (Outcome.NotAProductPath, null);
        }

        var item = items.FirstOrDefault(
            i => string.Equals(GallerySlugs.SlugFor(i, locale), slug, StringComparison.OrdinalIgnoreCase));

        if (item is null) return (Outcome.ProductNotFound, null);

        return (Outcome.Resolved, BuildTags(item, locale));
    }

    /// <summary>
    /// The current path for a product whose URL was minted under the pre-2026-08-17 slug
    /// algorithm, or null if this path is not a stale slug for anything.
    ///
    /// Asked only after the current-slug lookup has already missed, so this is what stands
    /// between "we corrected the slugs" and "every gallery URL ever shared or indexed now
    /// 404s". Matching against the OLD algorithm rather than a hard-coded list of the 16
    /// affected URLs means it keeps working for titles edited after the change, and there is
    /// no list to forget to update.
    /// </summary>
    public async Task<string?> TryResolveLegacyAsync(string path, CancellationToken ct)
    {
        if (!GallerySlugs.TryParsePath(path, out var locale, out var slug)) return null;

        IReadOnlyList<GalleryItem> items;
        try { items = await _gallery.GetAsync(ct); }
        catch { return null; }

        var item = items.FirstOrDefault(
            i => string.Equals(GallerySlugs.LegacySlugFor(i, locale), slug, StringComparison.OrdinalIgnoreCase));

        if (item is null) return null;

        // Unreachable in practice — an identical slug would have matched on the current
        // algorithm and never got here — but a product page that redirects to itself is an
        // infinite loop, so it is not worth leaving to reasoning.
        if (string.Equals(GallerySlugs.SlugFor(item, locale), slug, StringComparison.OrdinalIgnoreCase))
            return null;

        return GallerySlugs.PathFor(item, locale);
    }

    private static readonly Dictionary<string, string> OgLocale = new()
    {
        ["bg"] = "bg_BG",
        ["en"] = "en_GB",
        ["el"] = "el_GR",
    };

    /// <summary>
    /// The tag block, matching the shape scripts/generate-seo-manifest.mjs emits for static
    /// routes so the two cannot look different to a crawler.
    /// </summary>
    private static string BuildTags(GalleryItem item, string locale)
    {
        var title = $"{GallerySlugs.TitleFor(item, locale)} | NVC Home4You";
        var description = Snippet(GallerySlugs.DescriptionFor(item, locale), 155);
        var url = GallerySlugs.UrlFor(item, locale);

        // The product photo, not the site-wide default. Sharing a specific model into
        // Viber or Facebook previously showed the same generic image for every one of them.
        var image = AbsoluteImage(item.CoverUrl);

        var ogLocale = OgLocale.TryGetValue(locale, out var ol) ? ol : locale;

        var lines = new List<string>
        {
            $"<title>{EscText(title)}</title>",
            $"<meta name=\"description\" content=\"{EscAttr(description)}\" />",
            "<meta name=\"robots\" content=\"index,follow,max-image-preview:large\" />",
            "<meta property=\"og:site_name\" content=\"NVC Home4You\" />",
            "<meta property=\"og:type\" content=\"product\" />",
            $"<meta property=\"og:locale\" content=\"{ogLocale}\" />",
        };

        foreach (var (loc, _) in GallerySlugs.Locales)
        {
            if (loc == locale) continue;
            if (OgLocale.TryGetValue(loc, out var alt))
                lines.Add($"<meta property=\"og:locale:alternate\" content=\"{alt}\" />");
        }

        lines.Add($"<meta property=\"og:title\" content=\"{EscAttr(title)}\" />");
        lines.Add($"<meta property=\"og:description\" content=\"{EscAttr(description)}\" />");
        lines.Add($"<meta property=\"og:url\" content=\"{EscAttr(url)}\" />");

        if (image is not null)
        {
            lines.Add($"<meta property=\"og:image\" content=\"{EscAttr(image)}\" />");
            lines.Add($"<meta property=\"og:image:secure_url\" content=\"{EscAttr(image)}\" />");
            lines.Add($"<meta property=\"og:image:alt\" content=\"{EscAttr(title)}\" />");
        }

        lines.Add("<meta name=\"twitter:card\" content=\"summary_large_image\" />");
        lines.Add($"<meta name=\"twitter:title\" content=\"{EscAttr(title)}\" />");
        lines.Add($"<meta name=\"twitter:description\" content=\"{EscAttr(description)}\" />");
        if (image is not null)
            lines.Add($"<meta name=\"twitter:image\" content=\"{EscAttr(image)}\" />");

        // THE FIX. This used to say "https://nvc-home4you.eu/".
        lines.Add($"<link rel=\"canonical\" href=\"{EscAttr(url)}\" />");

        // Reciprocal alternates across all three locales, matching what
        // sitemap-gallery.xml already advertises for the same item.
        foreach (var (loc, _) in GallerySlugs.Locales)
            lines.Add($"<link rel=\"alternate\" hreflang=\"{loc}\" href=\"{EscAttr(GallerySlugs.UrlFor(item, loc))}\" />");

        lines.Add($"<link rel=\"alternate\" hreflang=\"x-default\" href=\"{EscAttr(GallerySlugs.UrlFor(item, "en"))}\" />");

        return string.Join("\n    ", lines);
    }

    /// <summary>
    /// Absolute URL for the social image, or null when the item has no photo.
    ///
    /// Relative because gallery covers are served from /api/img/...; Facebook and LinkedIn
    /// discard a relative og:image outright rather than resolving it against the page.
    /// </summary>
    private static string? AbsoluteImage(string? coverUrl)
    {
        if (string.IsNullOrWhiteSpace(coverUrl)) return null;
        if (coverUrl.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
            || coverUrl.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
        {
            return coverUrl;
        }

        return GallerySlugs.SiteUrl + (coverUrl.StartsWith('/') ? coverUrl : "/" + coverUrl);
    }

    /// <summary>
    /// Plain-text summary of a description, for a meta tag.
    ///
    /// Descriptions are rich text from Quickbase, so the markup has to come out — a
    /// description tag full of &lt;p&gt; renders as literal angle brackets in a search result.
    /// Cut on a word boundary so the snippet does not end mid-word.
    /// </summary>
    public static string Snippet(string? html, int max)
    {
        if (string.IsNullOrWhiteSpace(html)) return "";

        var text = Regex.Replace(html, "<[^>]+>", " ");
        text = System.Net.WebUtility.HtmlDecode(text);
        text = Regex.Replace(text, @"\s+", " ").Trim();

        if (text.Length <= max) return text;

        var cut = text[..max];
        var lastSpace = cut.LastIndexOf(' ');
        if (lastSpace > max / 2) cut = cut[..lastSpace];

        return cut.TrimEnd(',', '.', ';', ':', ' ') + "…";
    }

    private static string EscAttr(string s) => s
        .Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    private static string EscText(string s) => s
        .Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
