// Generated from the NVC-HOME4YOU catalogue (2026 edition).
// Codes, names, prices and inclusion all follow the printed catalogue; the
// thumbnails are cropped from the same pages. Regenerate rather than edit.

// 135 decors, 16 mm polyurethane -- included in the house price
export const FACADE_PANEL_OPTIONS = [
  { key: 'd-001', code: 'D-001', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#9a9da4', thumb: 'thumbs/panels/d-001.webp' },
  { key: 'd-002', code: 'D-002', en: 'Light brown sand', bg: 'Светло кафяв пясък', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#826a65', thumb: 'thumbs/panels/d-002.webp' },
  { key: 'd-003', code: 'D-003', en: 'Desert yellow', bg: 'Пустинно жълто', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#e9cc80', thumb: 'thumbs/panels/d-003.webp' },
  { key: 'd-004', code: 'D-004', en: 'Pine wood', bg: 'Борово дърво', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#cd5930', thumb: 'thumbs/panels/d-004.webp' },
  { key: 'd-005', code: 'D-005', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#dfdee0', thumb: 'thumbs/panels/d-005.webp' },
  { key: 'd-006', code: 'D-006', en: 'Brick red sand', bg: 'Тухлено червен пясък', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#c0412a', thumb: 'thumbs/panels/d-006.webp' },
  { key: 'd-007', code: 'D-007', en: 'Light grey', bg: 'Светло сиво', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#ababad', thumb: 'thumbs/panels/d-007.webp' },
  { key: 'd-008', code: 'D-008', en: 'Pale beige', bg: 'Бледо бежово', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#c8b7ab', thumb: 'thumbs/panels/d-008.webp' },
  { key: 'd-009', code: 'D-009', en: 'Ivory', bg: 'Слонова кост', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#c4c3bd', thumb: 'thumbs/panels/d-009.webp' },
  { key: 'd-010', code: 'D-010', en: 'Deep blue', bg: 'Наситено синьо', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#565e9e', thumb: 'thumbs/panels/d-010.webp' },
  { key: 'd-011', code: 'D-011', en: 'Sesame marble', bg: 'Сусамов мрамор', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#b1b0b1', thumb: 'thumbs/panels/d-011.webp' },
  { key: 'd-012', code: 'D-012', en: 'Cream beige', bg: 'Кремаво бежово', groupEn: 'Seven brick', groupBg: 'Седем тухли', swatch: '#e4dc9a', thumb: 'thumbs/panels/d-012.webp' },
  { key: 'd-013', code: 'D-013', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Three brick', groupBg: 'Три тухли', swatch: '#6f7175', thumb: 'thumbs/panels/d-013.webp' },
  { key: 'd-014', code: 'D-014', en: 'Light brown sand', bg: 'Светло кафяв пясък', groupEn: 'Three brick', groupBg: 'Три тухли', swatch: '#755f60', thumb: 'thumbs/panels/d-014.webp' },
  { key: 'd-015', code: 'D-015', en: 'Desert yellow', bg: 'Пустинно жълто', groupEn: 'Three brick', groupBg: 'Три тухли', swatch: '#d9c48a', thumb: 'thumbs/panels/d-015.webp' },
  { key: 'd-016', code: 'D-016', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Three brick', groupBg: 'Три тухли', swatch: '#d4d5d7', thumb: 'thumbs/panels/d-016.webp' },
  { key: 'd-017', code: 'D-017', en: 'Pale beige sand', bg: 'Бледо бежов пясък', groupEn: 'Three brick', groupBg: 'Три тухли', swatch: '#bfac9e', thumb: 'thumbs/panels/d-017.webp' },
  { key: 'd-018', code: 'D-018', en: 'Ivory', bg: 'Слонова кост', groupEn: 'Three brick', groupBg: 'Три тухли', swatch: '#d7d5c7', thumb: 'thumbs/panels/d-018.webp' },
  { key: 'd-019', code: 'D-019', en: 'Golden granite', bg: 'Златен гранит', groupEn: 'Three brick', groupBg: 'Три тухли', swatch: '#a09180', thumb: 'thumbs/panels/d-019.webp' },
  { key: 'd-020', code: 'D-020', en: 'Cream sand', bg: 'Кремав пясък', groupEn: 'Three brick', groupBg: 'Три тухли', swatch: '#dbc9a1', thumb: 'thumbs/panels/d-020.webp' },
  { key: 'd-021', code: 'D-021', en: 'Brick red sand', bg: 'Тухлено червен пясък', groupEn: 'Three brick', groupBg: 'Три тухли', swatch: '#b6442f', thumb: 'thumbs/panels/d-021.webp' },
  { key: 'd-022', code: 'D-022', en: 'Multicolour brick', bg: 'Многоцветна тухла', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#a56560', thumb: 'thumbs/panels/d-022.webp' },
  { key: 'd-023', code: 'D-023', en: 'Antique grey brick', bg: 'Антична сива тухла', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#586e76', thumb: 'thumbs/panels/d-023.webp' },
  { key: 'd-024', code: 'D-024', en: 'Red brick, grey grout', bg: 'Червена тухла, сива фуга', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#b44242', thumb: 'thumbs/panels/d-024.webp' },
  { key: 'd-025', code: 'D-025', en: 'Ivory', bg: 'Слонова кост', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#d7d7d3', thumb: 'thumbs/panels/d-025.webp' },
  { key: 'd-026', code: 'D-026', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#f0f1f2', thumb: 'thumbs/panels/d-026.webp' },
  { key: 'd-027', code: 'D-027', en: 'Orange', bg: 'Оранжево', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#e35c13', thumb: 'thumbs/panels/d-027.webp' },
  { key: 'd-028', code: 'D-028', en: 'Pale beige sand', bg: 'Бледо бежов пясък', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#cbb6a6', thumb: 'thumbs/panels/d-028.webp' },
  { key: 'd-029', code: 'D-029', en: 'Cream sand', bg: 'Кремав пясък', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#dfcd8f', thumb: 'thumbs/panels/d-029.webp' },
  { key: 'd-030', code: 'D-030', en: 'Black sand', bg: 'Черен пясък', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#3d4246', thumb: 'thumbs/panels/d-030.webp' },
  { key: 'd-031', code: 'D-031', en: 'Silver metallic', bg: 'Сребрист металик', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#c1c2c1', thumb: 'thumbs/panels/d-031.webp' },
  { key: 'd-032', code: 'D-032', en: 'Light brown sand', bg: 'Светло кафяв пясък', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#856a63', thumb: 'thumbs/panels/d-032.webp' },
  { key: 'd-033', code: 'D-033', en: 'Sesame marble', bg: 'Сусамов мрамор', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#aeb0b2', thumb: 'thumbs/panels/d-033.webp' },
  { key: 'd-034', code: 'D-034', en: 'Fine marble', bg: 'Ситен мрамор', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#bbbcb8', thumb: 'thumbs/panels/d-034.webp' },
  { key: 'd-035', code: 'D-035', en: 'Terrazzo', bg: 'Терацо', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#adaca7', thumb: 'thumbs/panels/d-035.webp' },
  { key: 'd-036', code: 'D-036', en: 'Double line, sesame', bg: 'Двойна линия, сусам', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#cfd2d6', thumb: 'thumbs/panels/d-036.webp' },
  { key: 'd-037', code: 'D-037', en: 'Wenge', bg: 'Венге', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#a04e24', thumb: 'thumbs/panels/d-037.webp' },
  { key: 'd-038', code: 'D-038', en: 'Yellow terrazzo', bg: 'Жълто терацо', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#b2aa94', thumb: 'thumbs/panels/d-038.webp' },
  { key: 'd-039', code: 'D-039', en: 'Golden granite', bg: 'Златен гранит', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#a09589', thumb: 'thumbs/panels/d-039.webp' },
  { key: 'd-040', code: 'D-040', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#767b86', thumb: 'thumbs/panels/d-040.webp' },
  { key: 'd-041', code: 'D-041', en: 'Cherry marble', bg: 'Черешов мрамор', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#bca086', thumb: 'thumbs/panels/d-041.webp' },
  { key: 'd-042', code: 'D-042', en: 'Natural stone', bg: 'Натурален камък', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#7c7570', thumb: 'thumbs/panels/d-042.webp' },
  { key: 'd-043', code: 'D-043', en: 'Light grey', bg: 'Светло сиво', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#a1a0a3', thumb: 'thumbs/panels/d-043.webp' },
  { key: 'd-044', code: 'D-044', en: 'Check, fine marble', bg: 'Каре, ситен мрамор', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#c0c3c6', thumb: 'thumbs/panels/d-044.webp' },
  { key: 'd-045', code: 'D-045', en: 'Red granite', bg: 'Червен гранит', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#a0584a', thumb: 'thumbs/panels/d-045.webp' },
  { key: 'd-046', code: 'D-046', en: 'Deep blue', bg: 'Наситено синьо', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#52568b', thumb: 'thumbs/panels/d-046.webp' },
  { key: 'd-047', code: 'D-047', en: 'Grey brick, white grout', bg: 'Сива тухла, бяла фуга', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#61635e', thumb: 'thumbs/panels/d-047.webp' },
  { key: 'd-048', code: 'D-048', en: 'Sesame dots', bg: 'Сусамови точки', groupEn: 'Spray render · flat', groupBg: 'Пръскана мазилка · плосък', swatch: '#b1b5b5', thumb: 'thumbs/panels/d-048.webp' },
  { key: 'd-049', code: 'D-049', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Spray render · centre bevelled groove', groupBg: 'Пръскана мазилка · среден скосен канал', swatch: '#e0e0e2', thumb: 'thumbs/panels/d-049.webp' },
  { key: 'd-050', code: 'D-050', en: 'Pine wood', bg: 'Борово дърво', groupEn: 'Spray render · centre bevelled groove', groupBg: 'Пръскана мазилка · среден скосен канал', swatch: '#c04c21', thumb: 'thumbs/panels/d-050.webp' },
  { key: 'd-051', code: 'D-051', en: 'Light grey', bg: 'Светло сиво', groupEn: 'Spray render · centre bevelled groove', groupBg: 'Пръскана мазилка · среден скосен канал', swatch: '#8f8f91', thumb: 'thumbs/panels/d-051.webp' },
  { key: 'd-052', code: 'D-052', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Spray render · centre bevelled groove', groupBg: 'Пръскана мазилка · среден скосен канал', swatch: '#7a7d7f', thumb: 'thumbs/panels/d-052.webp' },
  { key: 'd-053', code: 'D-053', en: 'Orange', bg: 'Оранжево', groupEn: 'Spray render · centre bevelled groove', groupBg: 'Пръскана мазилка · среден скосен канал', swatch: '#e46322', thumb: 'thumbs/panels/d-053.webp' },
  { key: 'd-054', code: 'D-054', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Spray render · centre straight groove', groupBg: 'Пръскана мазилка · среден прав канал', swatch: '#d8d7d7', thumb: 'thumbs/panels/d-054.webp' },
  { key: 'd-055', code: 'D-055', en: 'Ivory', bg: 'Слонова кост', groupEn: 'Spray render · centre straight groove', groupBg: 'Пръскана мазилка · среден прав канал', swatch: '#d3d1cc', thumb: 'thumbs/panels/d-055.webp' },
  { key: 'd-056', code: 'D-056', en: 'Desert yellow', bg: 'Пустинно жълто', groupEn: 'Spray render · centre straight groove', groupBg: 'Пръскана мазилка · среден прав канал', swatch: '#b4a36e', thumb: 'thumbs/panels/d-056.webp' },
  { key: 'd-057', code: 'D-057', en: 'Brick red', bg: 'Тухлено червено', groupEn: 'Spray render · centre straight groove', groupBg: 'Пръскана мазилка · среден прав канал', swatch: '#961f18', thumb: 'thumbs/panels/d-057.webp' },
  { key: 'd-058', code: 'D-058', en: 'Light brown sand', bg: 'Светло кафяв пясък', groupEn: 'Spray render · centre straight groove', groupBg: 'Пръскана мазилка · среден прав канал', swatch: '#786163', thumb: 'thumbs/panels/d-058.webp' },
  { key: 'd-059', code: 'D-059', en: 'Cream beige', bg: 'Кремаво бежово', groupEn: 'Spray render · centre straight groove', groupBg: 'Пръскана мазилка · среден прав канал', swatch: '#cdc288', thumb: 'thumbs/panels/d-059.webp' },
  { key: 'd-060', code: 'D-060', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Spray render · centre straight groove', groupBg: 'Пръскана мазилка · среден прав канал', swatch: '#80848c', thumb: 'thumbs/panels/d-060.webp' },
  { key: 'd-061', code: 'D-061', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Wood grain · flat', groupBg: 'Дървесен слой · плосък', swatch: '#e4e2e1', thumb: 'thumbs/panels/d-061.webp' },
  { key: 'd-062', code: 'D-062', en: 'Ivory', bg: 'Слонова кост', groupEn: 'Wood grain · flat', groupBg: 'Дървесен слой · плосък', swatch: '#c7c6bf', thumb: 'thumbs/panels/d-062.webp' },
  { key: 'd-063', code: 'D-063', en: 'Wenge', bg: 'Венге', groupEn: 'Wood grain · flat', groupBg: 'Дървесен слой · плосък', swatch: '#aa6745', thumb: 'thumbs/panels/d-063.webp' },
  { key: 'd-064', code: 'D-064', en: 'Dark wenge', bg: 'Тъмно венге', groupEn: 'Wood grain · flat', groupBg: 'Дървесен слой · плосък', swatch: '#846356', thumb: 'thumbs/panels/d-064.webp' },
  { key: 'd-065', code: 'D-065', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Wood grain · flat', groupBg: 'Дървесен слой · плосък', swatch: '#808386', thumb: 'thumbs/panels/d-065.webp' },
  { key: 'd-066', code: 'D-066', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Wood grain · double straight groove', groupBg: 'Дървесен слой · двоен прав канал', swatch: '#eaeae7', thumb: 'thumbs/panels/d-066.webp' },
  { key: 'd-067', code: 'D-067', en: 'Wenge', bg: 'Венге', groupEn: 'Wood grain · double straight groove', groupBg: 'Дървесен слой · двоен прав канал', swatch: '#9b4a20', thumb: 'thumbs/panels/d-067.webp' },
  { key: 'd-068', code: 'D-068', en: 'Brick red sand', bg: 'Тухлено червен пясък', groupEn: 'Wood grain · double straight groove', groupBg: 'Дървесен слой · двоен прав канал', swatch: '#ba1317', thumb: 'thumbs/panels/d-068.webp' },
  { key: 'd-069', code: 'D-069', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#dcdbdb', thumb: 'thumbs/panels/d-069.webp' },
  { key: 'd-070', code: 'D-070', en: 'Ivory', bg: 'Слонова кост', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#c1bfbb', thumb: 'thumbs/panels/d-070.webp' },
  { key: 'd-071', code: 'D-071', en: 'Pine wood', bg: 'Борово дърво', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#ce5727', thumb: 'thumbs/panels/d-071.webp' },
  { key: 'd-072', code: 'D-072', en: 'Light brown sand', bg: 'Светло кафяв пясък', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#7c645e', thumb: 'thumbs/panels/d-072.webp' },
  { key: 'd-073', code: 'D-073', en: 'Light grey', bg: 'Светло сиво', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#b0b1b1', thumb: 'thumbs/panels/d-073.webp' },
  { key: 'd-074', code: 'D-074', en: 'Deep blue', bg: 'Наситено синьо', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#545887', thumb: 'thumbs/panels/d-074.webp' },
  { key: 'd-075', code: 'D-075', en: 'Wenge', bg: 'Венге', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#9c5025', thumb: 'thumbs/panels/d-075.webp' },
  { key: 'd-076', code: 'D-076', en: 'Golden wenge', bg: 'Златно венге', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#855c35', thumb: 'thumbs/panels/d-076.webp' },
  { key: 'd-077', code: 'D-077', en: 'Dark wenge', bg: 'Тъмно венге', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#784d36', thumb: 'thumbs/panels/d-077.webp' },
  { key: 'd-078', code: 'D-078', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#707478', thumb: 'thumbs/panels/d-078.webp' },
  { key: 'd-079', code: 'D-079', en: 'Coarse-grain oak', bg: 'Едрослоен дъб', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#99684c', thumb: 'thumbs/panels/d-079.webp' },
  { key: 'd-080', code: 'D-080', en: 'Mountain pine', bg: 'Планински бор', groupEn: 'Wood grain · centre bevelled groove', groupBg: 'Дървесен слой · среден скосен канал', swatch: '#b0944d', thumb: 'thumbs/panels/d-080.webp' },
  { key: 'd-081', code: 'D-081', en: 'Pale beige', bg: 'Бледо бежово', groupEn: 'Wood grain · centre straight groove', groupBg: 'Дървесен слой · среден прав канал', swatch: '#ccc0b9', thumb: 'thumbs/panels/d-081.webp' },
  { key: 'd-082', code: 'D-082', en: 'Pine wood', bg: 'Борово дърво', groupEn: 'Wood grain · centre straight groove', groupBg: 'Дървесен слой · среден прав канал', swatch: '#be6142', thumb: 'thumbs/panels/d-082.webp' },
  { key: 'd-083', code: 'D-083', en: 'Deep blue', bg: 'Наситено синьо', groupEn: 'Wood grain · centre straight groove', groupBg: 'Дървесен слой · среден прав канал', swatch: '#5d6191', thumb: 'thumbs/panels/d-083.webp' },
  { key: 'd-084', code: 'D-084', en: 'Golden wenge', bg: 'Златно венге', groupEn: 'Wood grain · centre straight groove', groupBg: 'Дървесен слой · среден прав канал', swatch: '#826a52', thumb: 'thumbs/panels/d-084.webp' },
  { key: 'd-085', code: 'D-085', en: 'Grey 7006', bg: 'Сиво 7006', groupEn: 'Wood grain · centre straight groove', groupBg: 'Дървесен слой · среден прав канал', swatch: '#91877d', thumb: 'thumbs/panels/d-085.webp' },
  { key: 'd-086', code: 'D-086', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#eae7e8', thumb: 'thumbs/panels/d-086.webp' },
  { key: 'd-087', code: 'D-087', en: 'Ivory', bg: 'Слонова кост', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#dbd9d4', thumb: 'thumbs/panels/d-087.webp' },
  { key: 'd-088', code: 'D-088', en: 'Jazz white marble', bg: 'Джаз бял мрамор', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#d7dbe1', thumb: 'thumbs/panels/d-088.webp' },
  { key: 'd-089', code: 'D-089', en: 'Gloss white', bg: 'Гланцово бяло', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#dfe1e1', thumb: 'thumbs/panels/d-089.webp' },
  { key: 'd-090', code: 'D-090', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#76797f', thumb: 'thumbs/panels/d-090.webp' },
  { key: 'd-091', code: 'D-091', en: 'Vietnamese wood', bg: 'Виетнамско дърво', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#bebab4', thumb: 'thumbs/panels/d-091.webp' },
  { key: 'd-092', code: 'D-092', en: 'Brick red', bg: 'Тухлено червено', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#bd341b', thumb: 'thumbs/panels/d-092.webp' },
  { key: 'd-093', code: 'D-093', en: 'Single-tone stone', bg: 'Едноцветен камък', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#858279', thumb: 'thumbs/panels/d-093.webp' },
  { key: 'd-094', code: 'D-094', en: 'Desert yellow', bg: 'Пустинно жълто', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#a69561', thumb: 'thumbs/panels/d-094.webp' },
  { key: 'd-095', code: 'D-095', en: 'Light brown sand', bg: 'Светло кафяв пясък', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#563d41', thumb: 'thumbs/panels/d-095.webp' },
  { key: 'd-096', code: 'D-096', en: 'Black sand', bg: 'Черен пясък', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#393939', thumb: 'thumbs/panels/d-096.webp' },
  { key: 'd-097', code: 'D-097', en: 'Coarse-grain oak', bg: 'Едрослоен дъб', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#a56e47', thumb: 'thumbs/panels/d-097.webp' },
  { key: 'd-098', code: 'D-098', en: 'Mountain pine', bg: 'Планински бор', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#b99f59', thumb: 'thumbs/panels/d-098.webp' },
  { key: 'd-099', code: 'D-099', en: 'Jade', bg: 'Нефрит', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#e7f0ef', thumb: 'thumbs/panels/d-099.webp' },
  { key: 'd-100', code: 'D-100', en: 'Zebrano', bg: 'Зебрано', groupEn: 'Flat panel', groupBg: 'Плосък панел', swatch: '#ce7246', thumb: 'thumbs/panels/d-100.webp' },
  { key: 'd-101', code: 'D-101', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Flat · centre straight groove', groupBg: 'Плосък · среден прав канал', swatch: '#dde4e3', thumb: 'thumbs/panels/d-101.webp' },
  { key: 'd-102', code: 'D-102', en: 'Coarse-grain oak', bg: 'Едрослоен дъб', groupEn: 'Flat · centre straight groove', groupBg: 'Плосък · среден прав канал', swatch: '#c98f5b', thumb: 'thumbs/panels/d-102.webp' },
  { key: 'd-103', code: 'D-103', en: 'Dark walnut', bg: 'Тъмен орех', groupEn: 'Flat · centre straight groove', groupBg: 'Плосък · среден прав канал', swatch: '#76554b', thumb: 'thumbs/panels/d-103.webp' },
  { key: 'd-104', code: 'D-104', en: 'Desert yellow', bg: 'Пустинно жълто', groupEn: 'Flat · centre straight groove', groupBg: 'Плосък · среден прав канал', swatch: '#bdb071', thumb: 'thumbs/panels/d-104.webp' },
  { key: 'd-105', code: 'D-105', en: 'Wenge', bg: 'Венге', groupEn: 'Flat · centre bevelled groove', groupBg: 'Плосък · среден скосен канал', swatch: '#8c4a22', thumb: 'thumbs/panels/d-105.webp' },
  { key: 'd-106', code: 'D-106', en: 'Coarse-grain oak', bg: 'Едрослоен дъб', groupEn: 'Flat · centre bevelled groove', groupBg: 'Плосък · среден скосен канал', swatch: '#a5774f', thumb: 'thumbs/panels/d-106.webp' },
  { key: 'd-107', code: 'D-107', en: 'Gloss white', bg: 'Гланцово бяло', groupEn: 'Flat · centre bevelled groove', groupBg: 'Плосък · среден скосен канал', swatch: '#c1c6c0', thumb: 'thumbs/panels/d-107.webp' },
  { key: 'd-108', code: 'D-108', en: 'Pine wood', bg: 'Борово дърво', groupEn: 'Flat · double bevelled groove', groupBg: 'Плосък · двоен скосен канал', swatch: '#bf4a1c', thumb: 'thumbs/panels/d-108.webp' },
  { key: 'd-109', code: 'D-109', en: 'Dark walnut', bg: 'Тъмен орех', groupEn: 'Flat · double bevelled groove', groupBg: 'Плосък · двоен скосен канал', swatch: '#793a2b', thumb: 'thumbs/panels/d-109.webp' },
  { key: 'd-110', code: 'D-110', en: 'Coarse-grain oak', bg: 'Едрослоен дъб', groupEn: 'Flat · double bevelled groove', groupBg: 'Плосък · двоен скосен канал', swatch: '#a77656', thumb: 'thumbs/panels/d-110.webp' },
  { key: 'd-111', code: 'D-111', en: 'Black sand', bg: 'Черен пясък', groupEn: 'Flat · double straight groove', groupBg: 'Плосък · двоен прав канал', swatch: '#303032', thumb: 'thumbs/panels/d-111.webp' },
  { key: 'd-112', code: 'D-112', en: 'Coarse-grain oak', bg: 'Едрослоен дъб', groupEn: 'Flat · double straight groove', groupBg: 'Плосък · двоен прав канал', swatch: '#996543', thumb: 'thumbs/panels/d-112.webp' },
  { key: 'd-113', code: 'D-113', en: 'Mountain pine', bg: 'Планински бор', groupEn: 'Flat · double straight groove', groupBg: 'Плосък · двоен прав канал', swatch: '#ac904a', thumb: 'thumbs/panels/d-113.webp' },
  { key: 'd-114', code: 'D-114', en: 'Ivory', bg: 'Слонова кост', groupEn: 'Stone strips', groupBg: 'Каменни ивици', swatch: '#cdcbc6', thumb: 'thumbs/panels/d-114.webp' },
  { key: 'd-115', code: 'D-115', en: 'Angel white', bg: 'Ангелско бяло', groupEn: 'Stone strips', groupBg: 'Каменни ивици', swatch: '#e7e6e6', thumb: 'thumbs/panels/d-115.webp' },
  { key: 'd-116', code: 'D-116', en: 'Pale beige', bg: 'Бледо бежово', groupEn: 'Stone strips', groupBg: 'Каменни ивици', swatch: '#c2b7af', thumb: 'thumbs/panels/d-116.webp' },
  { key: 'd-117', code: 'D-117', en: 'Light brown sand', bg: 'Светло кафяв пясък', groupEn: 'Stone strips', groupBg: 'Каменни ивици', swatch: '#8b7777', thumb: 'thumbs/panels/d-117.webp' },
  { key: 'd-118', code: 'D-118', en: 'Black sand', bg: 'Черен пясък', groupEn: 'Stone strips', groupBg: 'Каменни ивици', swatch: '#555555', thumb: 'thumbs/panels/d-118.webp' },
  { key: 'd-119', code: 'D-119', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Stone strips', groupBg: 'Каменни ивици', swatch: '#828486', thumb: 'thumbs/panels/d-119.webp' },
  { key: 'd-120', code: 'D-120', en: 'Sesame dots', bg: 'Сусамови точки', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#c1c4c7', thumb: 'thumbs/panels/d-120.webp' },
  { key: 'd-121', code: 'D-121', en: 'Grass green', bg: 'Тревисто зелено', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#64c193', thumb: 'thumbs/panels/d-121.webp' },
  { key: 'd-122', code: 'D-122', en: 'Light grey', bg: 'Светло сиво', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#919194', thumb: 'thumbs/panels/d-122.webp' },
  { key: 'd-123', code: 'D-123', en: 'Pine wood', bg: 'Борово дърво', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#9c3a15', thumb: 'thumbs/panels/d-123.webp' },
  { key: 'd-124', code: 'D-124', en: 'Light brown sand', bg: 'Светло кафяв пясък', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#745b54', thumb: 'thumbs/panels/d-124.webp' },
  { key: 'd-125', code: 'D-125', en: 'Dark walnut', bg: 'Тъмен орех', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#70453a', thumb: 'thumbs/panels/d-125.webp' },
  { key: 'd-126', code: 'D-126', en: 'Deep blue', bg: 'Наситено синьо', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#474c83', thumb: 'thumbs/panels/d-126.webp' },
  { key: 'd-127', code: 'D-127', en: 'Wenge', bg: 'Венге', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#a35129', thumb: 'thumbs/panels/d-127.webp' },
  { key: 'd-128', code: 'D-128', en: 'Golden wenge', bg: 'Златно венге', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#7f6347', thumb: 'thumbs/panels/d-128.webp' },
  { key: 'd-129', code: 'D-129', en: 'Black sand', bg: 'Черен пясък', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#3c3c3e', thumb: 'thumbs/panels/d-129.webp' },
  { key: 'd-130', code: 'D-130', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Slat panel', groupBg: 'Ламелен панел', swatch: '#5f6064', thumb: 'thumbs/panels/d-130.webp' },
  { key: 'd-131', code: 'D-131', en: 'Silver metallic', bg: 'Сребрист металик', groupEn: 'Wave', groupBg: 'Вълнообразен', swatch: '#b6b6b8', thumb: 'thumbs/panels/d-131.webp' },
  { key: 'd-132', code: 'D-132', en: 'Orange', bg: 'Оранжево', groupEn: 'Wave', groupBg: 'Вълнообразен', swatch: '#de5921', thumb: 'thumbs/panels/d-132.webp' },
  { key: 'd-133', code: 'D-133', en: 'Black sand', bg: 'Черен пясък', groupEn: 'Oak grain', groupBg: 'Дъбов слой', swatch: '#474648', thumb: 'thumbs/panels/d-133.webp' },
  { key: 'd-134', code: 'D-134', en: 'Antique grey', bg: 'Старинно сиво', groupEn: 'Oak grain', groupBg: 'Дъбов слой', swatch: '#6e7275', thumb: 'thumbs/panels/d-134.webp' },
  { key: 'd-135', code: 'D-135', en: 'Light grey', bg: 'Светло сиво', groupEn: 'Oak grain', groupBg: 'Дъбов слой', swatch: '#a0a09a', thumb: 'thumbs/panels/d-135.webp' },
]

// 21 vinyl decors -- included
export const VINYL_FLOOR_OPTIONS = [
  { key: 'floor-7005', code: '7005', en: 'Natural oak', bg: 'Натурален дъб', groupEn: '7000 series · Warm wood', groupBg: 'Серия 7000 · Топло дърво', swatch: '#af8d68', thumb: 'thumbs/floor/7005.webp' },
  { key: 'floor-7006', code: '7006', en: 'Smoked rustic', bg: 'Опушен рустик', groupEn: '7000 series · Warm wood', groupBg: 'Серия 7000 · Топло дърво', swatch: '#7e7d73', thumb: 'thumbs/floor/7006.webp' },
  { key: 'floor-7007', code: '7007', en: 'Copper walnut', bg: 'Меден орех', groupEn: '7000 series · Warm wood', groupBg: 'Серия 7000 · Топло дърво', swatch: '#8d6041', thumb: 'thumbs/floor/7007.webp' },
  { key: 'floor-7008', code: '7008', en: 'Rosewood', bg: 'Палисандър', groupEn: '7000 series · Warm wood', groupBg: 'Серия 7000 · Топло дърво', swatch: '#8d4d3a', thumb: 'thumbs/floor/7008.webp' },
  { key: 'floor-7009', code: '7009', en: 'Dark oak', bg: 'Тъмен дъб', groupEn: '7000 series · Warm wood', groupBg: 'Серия 7000 · Топло дърво', swatch: '#966c4d', thumb: 'thumbs/floor/7009.webp' },
  { key: 'floor-8005', code: '8005', en: 'Mahogany', bg: 'Махагон', groupEn: '8000 series · Classic wood', groupBg: 'Серия 8000 · Класическо дърво', swatch: '#98452e', thumb: 'thumbs/floor/8005.webp' },
  { key: 'floor-8006', code: '8006', en: 'Misty oak', bg: 'Мъглив дъб', groupEn: '8000 series · Classic wood', groupBg: 'Серия 8000 · Класическо дърво', swatch: '#7b7d81', thumb: 'thumbs/floor/8006.webp' },
  { key: 'floor-8007', code: '8007', en: 'Sand ash', bg: 'Пясъчен ясен', groupEn: '8000 series · Classic wood', groupBg: 'Серия 8000 · Класическо дърво', swatch: '#e8dac3', thumb: 'thumbs/floor/8007.webp' },
  { key: 'floor-8008', code: '8008', en: 'Silver oak', bg: 'Сребърен дъб', groupEn: '8000 series · Classic wood', groupBg: 'Серия 8000 · Класическо дърво', swatch: '#93928f', thumb: 'thumbs/floor/8008.webp' },
  { key: 'floor-8009', code: '8009', en: 'Golden oak', bg: 'Златен дъб', groupEn: '8000 series · Classic wood', groupBg: 'Серия 8000 · Класическо дърво', swatch: '#ae7d54', thumb: 'thumbs/floor/8009.webp' },
  { key: 'floor-9005', code: '9005', en: 'Scandinavian oak', bg: 'Скандинавски дъб', groupEn: '9000 series · Light and grey wood', groupBg: 'Серия 9000 · Светло и сиво дърво', swatch: '#bfa282', thumb: 'thumbs/floor/9005.webp' },
  { key: 'floor-9006', code: '9006', en: 'Polar white', bg: 'Полярно бяло', groupEn: '9000 series · Light and grey wood', groupBg: 'Серия 9000 · Светло и сиво дърво', swatch: '#cbd2dc', thumb: 'thumbs/floor/9006.webp' },
  { key: 'floor-9007', code: '9007', en: 'Stone grey oak', bg: 'Каменно сив дъб', groupEn: '9000 series · Light and grey wood', groupBg: 'Серия 9000 · Светло и сиво дърво', swatch: '#90939d', thumb: 'thumbs/floor/9007.webp' },
  { key: 'floor-9008', code: '9008', en: 'Smoked beige', bg: 'Опушено бежово', groupEn: '9000 series · Light and grey wood', groupBg: 'Серия 9000 · Светло и сиво дърво', swatch: '#998e7b', thumb: 'thumbs/floor/9008.webp' },
  { key: 'floor-9009', code: '9009', en: 'Dark cherry', bg: 'Тъмна череша', groupEn: '9000 series · Light and grey wood', groupBg: 'Серия 9000 · Светло и сиво дърво', swatch: '#7b4236', thumb: 'thumbs/floor/9009.webp' },
  { key: 'floor-9010', code: '9010', en: 'Classic oak', bg: 'Класически дъб', groupEn: '9000 series · Light and grey wood', groupBg: 'Серия 9000 · Светло и сиво дърво', swatch: '#c8a27e', thumb: 'thumbs/floor/9010.webp' },
  { key: 'floor-9011', code: '9011', en: 'Silver poplar', bg: 'Сребриста топола', groupEn: '9000 series · Light and grey wood', groupBg: 'Серия 9000 · Светло и сиво дърво', swatch: '#a4a09c', thumb: 'thumbs/floor/9011.webp' },
  { key: 'floor-9012', code: '9012', en: 'Anthracite oak', bg: 'Антрацитен дъб', groupEn: '9000 series · Light and grey wood', groupBg: 'Серия 9000 · Светло и сиво дърво', swatch: '#7f7b79', thumb: 'thumbs/floor/9012.webp' },
  { key: 'floor-9013', code: '9013', en: 'Dark concrete', bg: 'Тъмен бетон', groupEn: '9000 series · Stone and marble', groupBg: 'Серия 9000 · Камък и мрамор', swatch: '#696870', thumb: 'thumbs/floor/9013.webp' },
  { key: 'floor-9015', code: '9015', en: 'White marble', bg: 'Бял мрамор', groupEn: '9000 series · Stone and marble', groupBg: 'Серия 9000 · Камък и мрамор', swatch: '#c7cbcd', thumb: 'thumbs/floor/9015.webp' },
  { key: 'floor-9016', code: '9016', en: 'Black schist', bg: 'Черен шист', groupEn: '9000 series · Stone and marble', groupBg: 'Серия 9000 · Камък и мрамор', swatch: '#6a6a6c', thumb: 'thumbs/floor/9016.webp' },
]

// 6 herringbone decors -- surcharge quoted on request
export const HERRINGBONE_FLOOR_OPTIONS = [
  { key: 'yg5716', code: 'YG5716', en: 'Honey oak', bg: 'Медов дъб', swatch: '#b88146', thumb: 'thumbs/herringbone/yg5716.webp' },
  { key: 'yg5711', code: 'YG5711', en: 'Dark wenge', bg: 'Тъмен венге', swatch: '#80604d', thumb: 'thumbs/herringbone/yg5711.webp' },
  { key: 'yg5715', code: 'YG5715', en: 'Smoked grey', bg: 'Опушено сиво', swatch: '#512f23', thumb: 'thumbs/herringbone/yg5715.webp' },
  { key: 'yg5713', code: 'YG5713', en: 'Golden oak', bg: 'Златен дъб', swatch: '#bf9861', thumb: 'thumbs/herringbone/yg5713.webp' },
  { key: 'yg5712', code: 'YG5712', en: 'Sand oak', bg: 'Пясъчен дъб', swatch: '#9b7851', thumb: 'thumbs/herringbone/yg5712.webp' },
  { key: 'yg5717', code: 'YG5717', en: 'Mahogany', bg: 'Махагон', swatch: '#888371', thumb: 'thumbs/herringbone/yg5717.webp' },
]

// 30 UV decors -- included
export const UV_PANEL_OPTIONS = [
  { key: 'hh24342-1-lj', code: 'HH24342-1-LJ', swatch: '#f1f0ec', thumb: 'thumbs/uv/hh24342-1-lj.webp' },
  { key: 'hh24454-lj', code: 'HH24454-LJ', swatch: '#c5c3c1', thumb: 'thumbs/uv/hh24454-lj.webp' },
  { key: 'hh24740-lj', code: 'HH24740-LJ', swatch: '#e9e9d9', thumb: 'thumbs/uv/hh24740-lj.webp' },
  { key: 'ml1044', code: 'ML1044', swatch: '#f2e5c9', thumb: 'thumbs/uv/ml1044.webp' },
  { key: 'ml1050-1', code: 'ML1050-1', swatch: '#e1e3d8', thumb: 'thumbs/uv/ml1050-1.webp' },
  { key: 'ml1089', code: 'ML1089', swatch: '#eddaaa', thumb: 'thumbs/uv/ml1089.webp' },
  { key: 'ml1268-1', code: 'ML1268-1', swatch: '#c5c6c1', thumb: 'thumbs/uv/ml1268-1.webp' },
  { key: 'ml1274', code: 'ML1274', swatch: '#ebe5d1', thumb: 'thumbs/uv/ml1274.webp' },
  { key: 'ml3003', code: 'ML3003', swatch: '#d0c9ba', thumb: 'thumbs/uv/ml3003.webp' },
  { key: 'ml9004b', code: 'ML9004B', swatch: '#dcd3c8', thumb: 'thumbs/uv/ml9004b.webp' },
  { key: 'mt89136-g', code: 'MT89136-G', swatch: '#b8c5bd', thumb: 'thumbs/uv/mt89136-g.webp' },
  { key: 'mt89162-g', code: 'MT89162-G', swatch: '#d7d6ce', thumb: 'thumbs/uv/mt89162-g.webp' },
  { key: 'mt89165-g', code: 'MT89165-G', swatch: '#eceae5', thumb: 'thumbs/uv/mt89165-g.webp' },
  { key: 'mt9066-1-g', code: 'MT9066-1-G', swatch: '#e8e1d7', thumb: 'thumbs/uv/mt9066-1-g.webp' },
  { key: 'mt9068-g', code: 'MT9068-G', swatch: '#f2d390', thumb: 'thumbs/uv/mt9068-g.webp' },
  { key: 'mt9085-g', code: 'MT9085-G', swatch: '#dbd9d7', thumb: 'thumbs/uv/mt9085-g.webp' },
  { key: 'mt9088-g', code: 'MT9088-G', swatch: '#171714', thumb: 'thumbs/uv/mt9088-g.webp' },
  { key: 'mt9090-g', code: 'MT9090-G', swatch: '#c6b3a7', thumb: 'thumbs/uv/mt9090-g.webp' },
  { key: 'mt9098-g', code: 'MT9098-G', swatch: '#93857f', thumb: 'thumbs/uv/mt9098-g.webp' },
  { key: 'mt9116-g', code: 'MT9116-G', swatch: '#bccac0', thumb: 'thumbs/uv/mt9116-g.webp' },
  { key: 'mt9132-g', code: 'MT9132-G', swatch: '#d6d2c9', thumb: 'thumbs/uv/mt9132-g.webp' },
  { key: 'mt9138-g', code: 'MT9138-G', swatch: '#e3d7c7', thumb: 'thumbs/uv/mt9138-g.webp' },
  { key: 'mt9158-1-g', code: 'MT9158-1-G', swatch: '#ebedea', thumb: 'thumbs/uv/mt9158-1-g.webp' },
  { key: 'mt9159-1-g', code: 'MT9159-1-G', swatch: '#d2d1cd', thumb: 'thumbs/uv/mt9159-1-g.webp' },
  { key: 'uv-001', code: 'UV-001', swatch: '#929796', thumb: 'thumbs/uv/uv-001.webp' },
  { key: 'uv-002', code: 'UV-002', swatch: '#8a8886', thumb: 'thumbs/uv/uv-002.webp' },
  { key: 'uv-003', code: 'UV-003', swatch: '#969692', thumb: 'thumbs/uv/uv-003.webp' },
  { key: 'uv-004', code: 'UV-004', swatch: '#9fa09f', thumb: 'thumbs/uv/uv-004.webp' },
  { key: 'uv-005', code: 'UV-005', swatch: '#b39d88', thumb: 'thumbs/uv/uv-005.webp' },
  { key: '', code: 'ТЕРАЦО', swatch: '#f4f2f1', thumb: 'thumbs/uv/t-r.webp' },
]

// 24 decors: 6 marble + 18 quartz -- included
export const KITCHEN_BENCH_OPTIONS = [
  { key: '01', code: 'М-01', en: 'Silver dragon', bg: 'Сребърен дракон', groupEn: 'Marble', groupBg: 'Мрамор', swatch: '#17191b', thumb: 'thumbs/kitchen-bench/m-01.webp' },
  { key: '02', code: 'М-02', en: 'Fish white', bg: 'Рибешко бяло', groupEn: 'Marble', groupBg: 'Мрамор', swatch: '#dededf', thumb: 'thumbs/kitchen-bench/m-02.webp' },
  { key: '03', code: 'М-03', en: 'Cloud grey', bg: 'Облачно сиво', groupEn: 'Marble', groupBg: 'Мрамор', swatch: '#a8a3a3', thumb: 'thumbs/kitchen-bench/m-03.webp' },
  { key: '04', code: 'М-04', en: 'Pure white', bg: 'Чисто бяло', groupEn: 'Marble', groupBg: 'Мрамор', swatch: '#e1e0e3', thumb: 'thumbs/kitchen-bench/m-04.webp' },
  { key: '05', code: 'М-05', en: 'White jade', bg: 'Бял нефрит', groupEn: 'Marble', groupBg: 'Мрамор', swatch: '#e3e3e3', thumb: 'thumbs/kitchen-bench/m-05.webp' },
  { key: '06', code: 'М-06', en: 'Arista white', bg: 'Ариста бяло', groupEn: 'Marble', groupBg: 'Мрамор', swatch: '#e1e1e4', thumb: 'thumbs/kitchen-bench/m-06.webp' },
  { key: 'hf-1000', code: 'HF-1000', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#e9eaed', thumb: 'thumbs/kitchen-bench/hf-1000.webp' },
  { key: 'hf-7001', code: 'HF-7001', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#e4e4e6', thumb: 'thumbs/kitchen-bench/hf-7001.webp' },
  { key: 'jl-517', code: 'JL-517', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#dcdcdc', thumb: 'thumbs/kitchen-bench/jl-517.webp' },
  { key: 'jl-521', code: 'JL-521', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#efeef1', thumb: 'thumbs/kitchen-bench/jl-521.webp' },
  { key: 'jl-526', code: 'JL-526', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#eeecea', thumb: 'thumbs/kitchen-bench/jl-526.webp' },
  { key: 'jl-708', code: 'JL-708', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#c4bdbd', thumb: 'thumbs/kitchen-bench/jl-708.webp' },
  { key: 'jl-823', code: 'JL-823', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#ebeaea', thumb: 'thumbs/kitchen-bench/jl-823.webp' },
  { key: 'jl-832', code: 'JL-832', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#eaebef', thumb: 'thumbs/kitchen-bench/jl-832.webp' },
  { key: 'jl-b0031', code: 'JL-B0031', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#666b77', thumb: 'thumbs/kitchen-bench/jl-b0031.webp' },
  { key: 'jql-5601', code: 'JQL-5601', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#ced2da', thumb: 'thumbs/kitchen-bench/jql-5601.webp' },
  { key: 'jql-6602', code: 'JQL-6602', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#e3e2e2', thumb: 'thumbs/kitchen-bench/jql-6602.webp' },
  { key: 'jql-6609', code: 'JQL-6609', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#d7d9dd', thumb: 'thumbs/kitchen-bench/jql-6609.webp' },
  { key: 'jql-6630', code: 'JQL-6630', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#b8b7b6', thumb: 'thumbs/kitchen-bench/jql-6630.webp' },
  { key: 'jql-6651', code: 'JQL-6651', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#d7d9dd', thumb: 'thumbs/kitchen-bench/jql-6651.webp' },
  { key: 'jql-6653', code: 'JQL-6653', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#d1d1d2', thumb: 'thumbs/kitchen-bench/jql-6653.webp' },
  { key: 'jql-6657', code: 'JQL-6657', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#787d88', thumb: 'thumbs/kitchen-bench/jql-6657.webp' },
  { key: 'zs-01', code: 'ZS-01', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#22252e', thumb: 'thumbs/kitchen-bench/zs-01.webp' },
  { key: 'zs-02', code: 'ZS-02', en: '', bg: '', groupEn: 'Quartz', groupBg: 'Кварц', swatch: '#f3f3f5', thumb: 'thumbs/kitchen-bench/zs-02.webp' },
]

// 23 decors -- priced per selection, quoted on request
export const INTERIOR_PANEL_OPTIONS = [
  { key: 'ip-01', code: 'IP-01', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#f0eee7', thumb: 'thumbs/interior-panels/ip-01.webp' },
  { key: 'ip-02', code: 'IP-02', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#d3d1c6', thumb: 'thumbs/interior-panels/ip-02.webp' },
  { key: 'ip-03', code: 'IP-03', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#d0d0ca', thumb: 'thumbs/interior-panels/ip-03.webp' },
  { key: 'ip-04', code: 'IP-04', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#d7d8d6', thumb: 'thumbs/interior-panels/ip-04.webp' },
  { key: 'ip-05', code: 'IP-05', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#cccdc8', thumb: 'thumbs/interior-panels/ip-05.webp' },
  { key: 'ip-06', code: 'IP-06', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#f5f5f5', thumb: 'thumbs/interior-panels/ip-06.webp' },
  { key: 'ip-07', code: 'IP-07', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#f0f1ec', thumb: 'thumbs/interior-panels/ip-07.webp' },
  { key: 'ip-08', code: 'IP-08', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#3d4849', thumb: 'thumbs/interior-panels/ip-08.webp' },
  { key: 'ip-09', code: 'IP-09', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#bdb5b1', thumb: 'thumbs/interior-panels/ip-09.webp' },
  { key: 'ip-10', code: 'IP-10', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#d4d5d0', thumb: 'thumbs/interior-panels/ip-10.webp' },
  { key: 'ip-11', code: 'IP-11', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#cbc5c0', thumb: 'thumbs/interior-panels/ip-11.webp' },
  { key: 'ip-12', code: 'IP-12', groupEn: 'Smooth and matte', groupBg: 'Гладки и матови', swatch: '#f6f6f6', thumb: 'thumbs/interior-panels/ip-12.webp' },
  { key: 'ip-13', code: 'IP-13', groupEn: 'Wood decors', groupBg: 'Дървесни декори', swatch: '#a79070', thumb: 'thumbs/interior-panels/ip-13.webp' },
  { key: 'ip-14', code: 'IP-14', groupEn: 'Wood decors', groupBg: 'Дървесни декори', swatch: '#615748', thumb: 'thumbs/interior-panels/ip-14.webp' },
  { key: 'ip-15', code: 'IP-15', groupEn: 'Wood decors', groupBg: 'Дървесни декори', swatch: '#5d5842', thumb: 'thumbs/interior-panels/ip-15.webp' },
  { key: 'ip-16', code: 'IP-16', groupEn: 'Wood decors', groupBg: 'Дървесни декори', swatch: '#51352b', thumb: 'thumbs/interior-panels/ip-16.webp' },
  { key: 'ip-17', code: 'IP-17', groupEn: 'Textured', groupBg: 'Структурни', swatch: '#c3c5c5', thumb: 'thumbs/interior-panels/ip-17.webp' },
  { key: 'ip-18', code: 'IP-18', groupEn: 'Textured', groupBg: 'Структурни', swatch: '#b4b2ae', thumb: 'thumbs/interior-panels/ip-18.webp' },
  { key: 'ip-19', code: 'IP-19', groupEn: 'Textured', groupBg: 'Структурни', swatch: '#575b5e', thumb: 'thumbs/interior-panels/ip-19.webp' },
  { key: 'ip-20', code: 'IP-20', groupEn: 'Solid colours', groupBg: 'Плътни цветове', swatch: '#ccb06d', thumb: 'thumbs/interior-panels/ip-20.webp' },
  { key: 'ip-21', code: 'IP-21', groupEn: 'Solid colours', groupBg: 'Плътни цветове', swatch: '#c68f55', thumb: 'thumbs/interior-panels/ip-21.webp' },
  { key: 'ip-22', code: 'IP-22', groupEn: 'Solid colours', groupBg: 'Плътни цветове', swatch: '#3c2520', thumb: 'thumbs/interior-panels/ip-22.webp' },
  { key: 'ip-23', code: 'IP-23', groupEn: 'Solid colours', groupBg: 'Плътни цветове', swatch: '#3b4841', thumb: 'thumbs/interior-panels/ip-23.webp' },
]

// PET cabinet colours -- surcharge quoted on request
export const KITCHEN_PET_COLOUR_OPTIONS = [
  { key: 'pet-2001', code: '2001', swatch: '#fdfffe', finish: 'gloss' },
  { key: 'pet-2002', code: '2002', swatch: '#faffff', finish: 'matte' },
  { key: 'pet-2003', code: '2003', swatch: '#fffff5', finish: 'gloss' },
  { key: 'pet-2005', code: '2005', swatch: '#fffffa', finish: 'matte' },
  { key: 'pet-2006', code: '2006', swatch: '#a6a19d', finish: 'matte' },
  { key: 'pet-2007', code: '2007', swatch: '#b9b09d', finish: 'matte' },
  { key: 'pet-2008', code: '2008', swatch: '#a2a2a6', finish: 'matte' },
  { key: 'pet-2009', code: '2009', swatch: '#9a9081', finish: 'matte' },
  { key: 'pet-2010', code: '2010', swatch: '#9ea7b0', finish: 'matte' },
  { key: 'pet-2011', code: '2011', swatch: '#ccd5d8', finish: 'matte' },
  { key: 'pet-2012', code: '2012', swatch: '#3c3c40', finish: 'matte' },
  { key: 'pet-2013', code: '2013', swatch: '#343333', finish: 'matte' },
  { key: 'pet-2015', code: '2015', swatch: '#c3b9a5', finish: 'gloss' },
  { key: 'pet-2016', code: '2016', swatch: '#98999d', finish: 'gloss' },
  { key: 'pet-2017', code: '2017', swatch: '#819c8b', finish: 'matte' },
  { key: 'pet-2018', code: '2018', swatch: '#7d99a7', finish: 'matte' },
  { key: 'pet-2019', code: '2019', swatch: '#cbcbc2', finish: 'matte' },
  { key: 'pet-2020', code: '2020', swatch: '#cfcabd', finish: 'gloss' },
  { key: 'pet-2021', code: '2021', swatch: '#d0cbc3', finish: 'matte' },
  { key: 'pet-2022', code: '2022', swatch: '#cdcfd0', finish: 'matte' },
  { key: 'pet-2023', code: '2023', swatch: '#d1d4d3', finish: 'gloss' },
  { key: 'pet-2025', code: '2025', swatch: '#e4dbc7', finish: 'matte' },
  { key: 'pet-2026', code: '2026', swatch: '#c8beb4', finish: 'gloss' },
  { key: 'pet-2027', code: '2027', swatch: '#2a2929', finish: 'gloss' },
  { key: 'pet-2028', code: '2028', swatch: '#cbbc9e', finish: 'matte' },
  { key: 'pet-2029', code: '2029', swatch: '#ccc3af', finish: 'matte' },
  { key: 'pet-2030', code: '2030', swatch: '#bdddbf', finish: 'metallic' },
  { key: 'pet-2031', code: '2031', swatch: '#a7a398', finish: 'metallic' },
  { key: 'pet-2032', code: '2032', swatch: '#f5f5f5', finish: 'metallic' },
  { key: 'pet-2033', code: '2033', swatch: '#decbb4', finish: 'matte' },
  { key: 'pet-2035', code: '2035', swatch: '#6e8186', finish: 'matte' },
  { key: 'pet-2036', code: '2036', swatch: '#cbc3a8', finish: 'matte' },
  { key: 'pet-2037', code: '2037', swatch: '#dbccb4', finish: 'gloss' },
  { key: 'pet-2038', code: '2038', swatch: '#dbccb4', finish: 'matte' },
  { key: 'pet-2039', code: '2039', swatch: '#d4cdae', finish: 'gloss' },
  { key: 'pet-2040', code: '2040', swatch: '#beb69d', finish: 'metallic' },
  { key: 'pet-2041', code: '2041', swatch: '#ff524a', finish: 'matte' },
  { key: 'pet-2043', code: '2043', swatch: '#c7c1a8', finish: 'matte' },
]

// 8 decking decors -- decor does not change the balcony price
export const DECKING_OPTIONS = [
  { key: 't-01', code: 'T-01', swatch: '#a99678', thumb: 'thumbs/decking/t-01.webp' },
  { key: 't-02', code: 'T-02', swatch: '#8f7268', thumb: 'thumbs/decking/t-02.webp' },
  { key: 't-03', code: 'T-03', swatch: '#796d65', thumb: 'thumbs/decking/t-03.webp' },
  { key: 't-04', code: 'T-04', swatch: '#59514a', thumb: 'thumbs/decking/t-04.webp' },
  { key: 't-05', code: 'T-05', swatch: '#856b64', thumb: 'thumbs/decking/t-05.webp' },
  { key: 't-06', code: 'T-06', swatch: '#e0af72', thumb: 'thumbs/decking/t-06.webp' },
  { key: 't-07', code: 'T-07', swatch: '#666666', thumb: 'thumbs/decking/t-07.webp' },
  { key: 't-08', code: 'T-08', swatch: '#d6896c', thumb: 'thumbs/decking/t-08.webp' },
]

