using System;
using System.ComponentModel.DataAnnotations;

namespace Data.Entities;

// One image belonging to a house. Replaces the Quickbase images table, and is where the
// Blob migration and the SQL migration meet.
//
// The row stores an ImageKey, not a URL. A URL would bake in today's answer to "who serves
// this image" — Quickbase, Blob, or our own /api/img route — and every row would need
// rewriting each time that changed. The key is stable across all three, and ImageUrls turns
// it into whatever URL the current configuration calls for at response time.
public class HouseImage
{
    public int Id { get; set; }

    public int HouseId { get; set; }
    public House? House { get; set; }

    // Where the bytes live in Blob: "gallery/{houseId}/{guid}.{ext}". Generated by us, for
    // both admin uploads and imported images, so nothing inherits Quickbase's URL shape.
    [MaxLength(1024)] public string ImageKey { get; set; } = "";

    // The Quickbase attachment path this row was imported from ("up/…"), or null for images
    // added through the admin panel.
    //
    // This is what makes the import idempotent. ImageKey cannot be: it contains a freshly
    // minted GUID, so matching on it would make every re-run download and upload every image
    // again and insert a duplicate row. SourceKey is stable for an unchanged attachment, and
    // because Quickbase's path embeds the attachment version, replacing an image upstream
    // yields a different SourceKey — which is exactly the signal to re-upload.
    [MaxLength(1024)] public string? SourceKey { get; set; }

    // Shown as the cover when it sorts first. Explicit ordering because the admin panel needs
    // to reorder images, which the Quickbase import could only approximate by row order.
    public int SortOrder { get; set; }

    [MaxLength(400)] public string? AltText { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
}
